services:
    postgres:
        image: postgres:15-alpine
        environment:
            POSTGRES_PASSWORD: blogblog
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - BlogNet

volumes:
    postgres_data:

networks:
    BlogNet:
        driver: bridge