services:
    postgres:
        image: postgres:15-alpine
        environment:
            POSTGRES_PASSWORD: blogblog
            TZ: America/Sao_Paulo
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - BlogNet
    api:
        ports:
            - '5177:8080'
        build:
            dockerfile: api.dockerfile
        depends_on:
            - postgres
        networks:
            - BlogNet

    client:
        ports:
            - '4200:8080'
        build:
            dockerfile: client.dockerfile
        depends_on:
            - postgres
            - api
        networks:
            - BlogNet

volumes:
    postgres_data:

networks:
    BlogNet:
        driver: bridge
